### ISSUE TITLE
Appear.in is changing brand and URL

### ISSUE THREAD

**Issue by maciekgajewski** [treffynnon/whereby-com-helper-browser-extension#1]
Appear.in is re-branding to Whereby.com. Currently both URL works, but starting September 1st, only Whereby.com will work.
The Chrome extension needs to be updated accordingly.

**Comment by treffynnon** [comment]
Thank you for the heads up about their trademark dispute. I found the related news is in blog form over on https://medium.com/the-making-of-whereby/appear-in-is-now-whereby-b258d77d3ad9

**Comment by treffynnon** [comment]
This should now be fix in v1.2.2
